name: BioScore
channels:
  - pytorch
  - pyg
  - bioconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - aria2=1.37.0
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=24.2.0
  - backcall=0.2.0
  - blas=2.121
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gawk=5.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.8
  - importlib_metadata=7.0.1
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.84.2
  - libhwloc=2.11.1
  - libiconv=1.18
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libpng=1.6.47
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - multidict=6.0.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openbabel=3.1.1
  - openssl=3.5.0
  - packaging=24.1
  - parso=0.8.3
  - pcre2=10.45
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.46.2
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pyg=2.5.2
  - pygments=2.15.1
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-cluster=1.6.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=72.2.0
  - six=1.16.0
  - stack_data=0.2.0
  - tbb=2021.12.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - wget=1.21.4
  - wheel=0.44.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.2.6
  - yarl=1.9.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - argparse==1.4.0
    - atom3d==0.2.6
    - autograd==1.7.0
    - autograd-gamma==0.5.0
    - backports-shutil-get-terminal-size==1.0.0
    - beartype==0.18.5
    - biopandas==0.4.1
    - biopython==1.79
    - blosc2==2.5.1
    - cachetools==5.5.0
    - chardet==5.2.0
    - click==8.1.7
    - conda-pack==0.8.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - dill==0.3.8
    - e3nn==0.5.1
    - easy-parallel==0.1.6
    - easydict==1.13
    - einops==0.8.0
    - fair-esm==2.0.0
    - fasteners==0.19
    - filelock==3.15.4
    - fonttools==4.56.0
    - formulaic==1.1.1
    - freesasa==2.2.1
    - google-auth==2.34.0
    - google-auth-oauthlib==1.0.0
    - griddataformats==1.0.2
    - grpcio==1.66.1
    - h5py==3.11.0
    - importlib-metadata==8.4.0
    - importlib-resources==6.5.2
    - interface-meta==1.3.0
    - kiwisolver==1.4.7
    - lifelines==0.27.5
    - lmdb==1.5.1
    - markdown==3.7
    - matplotlib==3.9.4
    - mda-xdrlib==0.2.0
    - mdanalysis==2.7.0
    - mmtf-python==1.1.3
    - mpmath==1.3.0
    - mrcfile==1.5.4
    - msgpack==1.0.8
    - multipledispatch==1.0.0
    - multiprocess==0.70.16
    - ndindex==1.8
    - networkx==3.2.1
    - numexpr==2.10.1
    - numpy==1.23.5
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - pandas==2.2.2
    - pathos==0.3.2
    - pillow==10.4.0
    - pox==0.3.4
    - ppft==1.7.6.8
    - prody==2.4.1
    - protobuf==5.28.0
    - py-cpuinfo==9.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pyrr==0.10.3
    - python-dotenv==1.0.1
    - pytz==2024.1
    - rdkit-pypi==2022.3.5
    - reprint==0.6.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - seaborn==0.13.1
    - sympy==1.13.2
    - tables==3.9.2
    - tensorboard==2.12.1
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tzdata==2024.1
    - werkzeug==3.0.4
    - wrapt==1.17.2
    - zipp==3.20.1